import { Review } from "./types";

export const mockReviews: Review[] = [
  {
    id: "rev-001",
    pedimentoNumber: "25 01 3645 8100050",
    importerName: "Serviacero Especiales S.A. de C.V.",
    operationType: "Importacion Definitiva (A1)",
    status: "completed",
    createdAt: "2026-02-15T10:30:00Z",
    completedAt: "2026-02-15T10:45:00Z",
    documentsCount: 12,
    matchCount: 34,
    mismatchCount: 3,
    warningCount: 5,
    documents: [
      { id: "d1", name: "Pedimento AT2501392.pdf", type: "application/pdf", size: 245000, isPedimento: true },
      { id: "d2", name: "Factura Comercial FV25288.pdf", type: "application/pdf", size: 180000, isPedimento: false },
      { id: "d3", name: "Bill of Lading BL.pdf", type: "application/pdf", size: 156000, isPedimento: false },
      { id: "d4", name: "Packing List PL.pdf", type: "application/pdf", size: 98000, isPedimento: false },
      { id: "d5", name: "Carta Encomienda CE.pdf", type: "application/pdf", size: 67000, isPedimento: false },
    ],
    fields: [
      {
        id: "f1",
        fieldName: "RFC Importador",
        pedimentoValue: "SES0301013P2",
        documentValue: "SES0301013P2",
        documentSource: "Factura Comercial",
        status: "match",
      },
      {
        id: "f2",
        fieldName: "Peso Bruto (Kg)",
        pedimentoValue: "24,500.00",
        documentValue: "24,780.50",
        documentSource: "Bill of Lading",
        status: "mismatch",
        severity: "high",
        note: "Discrepancy of 280.5 Kg between pedimento and BL. May trigger audit.",
      },
      {
        id: "f3",
        fieldName: "Numero de BL",
        pedimentoValue: "JAYU1098003",
        documentValue: "JAYU1098003",
        documentSource: "Bill of Lading",
        status: "match",
      },
      {
        id: "f4",
        fieldName: "Valor Comercial (USD)",
        pedimentoValue: "$128,450.00",
        documentValue: "$128,450.00",
        documentSource: "Factura Comercial",
        status: "match",
      },
      {
        id: "f5",
        fieldName: "Fraccion Arancelaria",
        pedimentoValue: "7208.51.01",
        documentValue: "7208.51.02",
        documentSource: "Clasificacion Arancelaria",
        status: "mismatch",
        severity: "high",
        note: "Tariff fraction mismatch. Verify correct classification to avoid sanctions.",
      },
      {
        id: "f6",
        fieldName: "Pais de Origen",
        pedimentoValue: "CHN",
        documentValue: "CHN",
        documentSource: "Certificado de Origen",
        status: "match",
      },
      {
        id: "f7",
        fieldName: "Tipo de Cambio",
        pedimentoValue: "17.2450",
        documentValue: "17.2310",
        documentSource: "DOF Reference",
        status: "warning",
        severity: "medium",
        note: "Exchange rate difference of 0.014. Verify DOF publication date used.",
      },
      {
        id: "f8",
        fieldName: "Numero de Contenedor",
        pedimentoValue: "JAYU1098003",
        documentValue: "JAYU1098003",
        documentSource: "EIR",
        status: "match",
      },
      {
        id: "f9",
        fieldName: "Nombre del Proveedor",
        pedimentoValue: "Norbright Industry Co.",
        documentValue: "Norbright Industry Co. Ltd",
        documentSource: "Factura Comercial",
        status: "warning",
        severity: "low",
        note: "Minor name difference. Abbreviation vs full name.",
      },
      {
        id: "f10",
        fieldName: "Cantidad de Bultos",
        pedimentoValue: "45",
        documentValue: "45",
        documentSource: "Packing List",
        status: "match",
      },
      {
        id: "f11",
        fieldName: "INCOTERM",
        pedimentoValue: "CFR",
        documentValue: "CFR",
        documentSource: "Factura Comercial",
        status: "match",
      },
      {
        id: "f12",
        fieldName: "Puerto de Entrada",
        pedimentoValue: "Manzanillo",
        documentValue: "Manzanillo",
        documentSource: "Bill of Lading",
        status: "match",
      },
    ],
  },
  {
    id: "rev-002",
    pedimentoNumber: "25 01 3645 8100051",
    importerName: "Nueva Incal S.A. de C.V.",
    operationType: "Importacion Definitiva (A1)",
    status: "in_progress",
    createdAt: "2026-02-17T14:20:00Z",
    documentsCount: 8,
    matchCount: 0,
    mismatchCount: 0,
    warningCount: 0,
    documents: [
      { id: "d6", name: "Pedimento Simplificado.pdf", type: "application/pdf", size: 210000, isPedimento: true },
      { id: "d7", name: "Invoice 26EZ705.pdf", type: "application/pdf", size: 145000, isPedimento: false },
    ],
    fields: [],
  },
  {
    id: "rev-003",
    pedimentoNumber: "25 01 3645 8100048",
    importerName: "Grupo Industrial MX S.A.",
    operationType: "Exportacion Definitiva (K1)",
    status: "completed",
    createdAt: "2026-02-10T09:15:00Z",
    completedAt: "2026-02-10T09:32:00Z",
    documentsCount: 6,
    matchCount: 28,
    mismatchCount: 0,
    warningCount: 2,
    documents: [],
    fields: [
      {
        id: "f20",
        fieldName: "RFC Exportador",
        pedimentoValue: "GIM990812AB3",
        documentValue: "GIM990812AB3",
        documentSource: "Carta Encomienda",
        status: "match",
      },
      {
        id: "f21",
        fieldName: "Valor Declarado (MXN)",
        pedimentoValue: "$2,456,780.00",
        documentValue: "$2,456,780.00",
        documentSource: "Factura Comercial",
        status: "match",
      },
    ],
  },
  {
    id: "rev-004",
    pedimentoNumber: "25 01 3645 8100052",
    importerName: "Aceros del Norte S.A.",
    operationType: "Importacion Temporal (F5)",
    status: "completed",
    createdAt: "2026-02-12T16:00:00Z",
    completedAt: "2026-02-12T16:22:00Z",
    documentsCount: 10,
    matchCount: 31,
    mismatchCount: 1,
    warningCount: 3,
    documents: [],
    fields: [],
  },
];
